// Builds data/deck/*.json into build/seed.sql for loading into D1.
// The audio column is preserved on conflict — it is managed by gen_audio.mjs.
// Run: node scripts/load_deck.mjs
import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const deckDir = join(root, 'data', 'deck');
const q = (v) => (v == null || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

let sql = '-- generated by load_deck.mjs\n';
let total = 0;

for (const file of readdirSync(deckDir).filter((f) => f.endsWith('.json')).sort()) {
  const deck = JSON.parse(readFileSync(join(deckDir, file), 'utf8'));
  const course = deck.meta?.course;
  if (!course) throw new Error(`${file}: meta.course is missing`);

  for (const c of deck.cards) {
    const term = c.term ?? c.pt ?? c.en;
    const ex = c.ex_t ?? c.ex_pt ?? c.ex_en;
    if (!term || !c.id || !c.trans) throw new Error(`${file}: broken card ${JSON.stringify(c).slice(0, 80)}`);
    sql += `INSERT INTO cards (id, course, term, trans, pos, gender, note, ex_t, ex_trans, tags, freq) VALUES (` +
      [q(c.id), q(course), q(term), q(c.trans), q(c.pos), q(c.gender), q(c.note), q(ex), q(c.ex_trans),
       q(JSON.stringify(c.tags ?? [])), c.freq ?? 'NULL'].join(', ') +
      `) ON CONFLICT(id) DO UPDATE SET course = excluded.course, term = excluded.term, trans = excluded.trans, ` +
      `pos = excluded.pos, gender = excluded.gender, note = excluded.note, ex_t = excluded.ex_t, ` +
      `ex_trans = excluded.ex_trans, tags = excluded.tags, freq = excluded.freq;\n`;
    total++;
  }
  console.log(`${file}: ${deck.cards.length} cards (${course})`);
}

mkdirSync(join(root, 'build'), { recursive: true });
writeFileSync(join(root, 'build', 'seed.sql'), sql);
console.log(`total ${total} → build/seed.sql`);
